version: '3.8'
services:
  comunio_mysql_db:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_DATABASE=comunio
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - '3306:3306'